function []=bridge_plot_swedish_v3(n,tendata)
%% Plot initialisation
startday=n-3;
X1=startday:10/1440:n+1;
plotdata=NaN(length(X1),size(tendata,2));
plotdata(:,1)=X1';
index=1;
for i=1:size(plotdata,1)
    line2=find(plotdata(index,1)==tendata(:,1));
    if line2>1
%         if size(tendata,1)>index    --> kom också ihåg nederbördsdygnet!
            plotdata(i,:)=tendata(line2,:);
            
%         end
    end
    index=index+1;
end

figure1 = figure('Position',[10 5 460 900],'color',[1 1 1]);

xlabels={'0',' ',' ','6',' ',' ','12',' ',' ','18',' ',' ','0'...
    ,' ',' ','6',' ',' ','12',' ',' ','18',' ',' ','0'...
    ,' ',' ','6',' ',' ','12',' ',' ','18',' ',' ','0'...
    ,' ',' ','6',' ',' ','12',' ',' ','18',' ',' ','0'};
xlabels2={' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '...
    ,' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '...
    ,' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '...
    ,' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '};

tsize=10;
asize=8;
ysize=10;

%% Temperature
Temp_ylim_lo = -15; Temp_ylim_up = 15;
axes1 = axes('Parent',figure1,...
    'YLim',[Temp_ylim_lo Temp_ylim_up],...
    'YTick',[-30 -25 -20 -15 -10 -5 0 5 10 15 20 25 30 35 40],...
    'YTickLabel',[-30 {''} -20 {''} -10 {''} 0 {''} 10 {''} 20 {''} 30 {''} 40],...
    'XLim',[n-3 n+1],...
    'Position',[0.12 0.89 0.85 0.07],...
    'FontSize',asize,...
    'XTickLabel',xlabels,...
    'XTick',n-3:2/24:n+1,...
    'TickLength',[0.005 0.1],...
    'YGrid','on');
box('on');
hold('all');
title('Lufttemperatur','FontSize', tsize);
%     plot1=plot(plotdata(:,1),plotdata(:,20),plotdata(:,1),plotdata(:,22),plotdata(:,1),plotdata(:,11));
plot1=plot(plotdata(:,1),plotdata(:,11));
%     set(plot1(1),'DisplayName','100 masl','Color',[1 0 0],'LineStyle','-');
%     set(plot1(2),'DisplayName','5 masl','Color',[0 0 1],'LineStyle','-');
set(plot1,'DisplayName','120 masl (WXT520)','Color',[1 0 0],'LineStyle','-');

%     legend1 = legend(axes1,'show');
%     set(legend1,'Position',[0.515 0.965 0.05 0.01],'Orientation','horizontal','FontSize',asize,...
%         'FontName','Arial');
ylabel('^oC','FontSize',ysize);

%% Dates labes
text(n-3+3.2,Temp_ylim_lo-0.34*(Temp_ylim_up - Temp_ylim_lo),datestr(n,29),'FontSize',asize)
text(n-3+2.2,Temp_ylim_lo-0.34*(Temp_ylim_up - Temp_ylim_lo),datestr(n-1,29),'FontSize',asize)
text(n-3+1.2,Temp_ylim_lo-0.34*(Temp_ylim_up - Temp_ylim_lo),datestr(n-2,29),'FontSize',asize)
text(n-3+0.2,Temp_ylim_lo-0.34*(Temp_ylim_up - Temp_ylim_lo),datestr(n-3,29),'FontSize',asize)

%% Relative humidity
axes1 = axes('Parent',figure1,...
    'YLim',[0 100],...
    'XLim',[n-3 n+1],...
    'Position',[0.12 0.76 0.85 0.07],...
    'FontSize',asize,...
    'YTickLabel',[0 25 50 75 100],...
    'YTick',0:25:100,...
    'XTickLabel',xlabels,...
    'XTick',n-3:2/24:n+1,...
    'TickLength',[0.005 0.1],...
    'YGrid','on');
box('on');
hold('all');
title('Relativ fuktighet','FontSize', tsize);
plot2=plot(plotdata(:,1),plotdata(:,12));
%     set(plot2,'DisplayName','Wind Dir','Color',[0 1 0],'LineStyle','-');

ylabel('%','FontSize',ysize);

%% Pressure
axes1 = axes('Parent',figure1,...
    'YLim',[960 1040],...
    'XLim',[n-3 n+1],...
    'Position',[0.12 0.64 0.85 0.07],...
    'FontSize',asize,...
    'XTickLabel',xlabels,...
    'XTick',n-3:2/24:n+1,...
    'YTickLabel',[960 980 1000 1020 1040],...
    'YTick',960:20:1040,...
    'TickLength',[0.005 0.1],...
    'YGrid','on');
box('on');
hold('all');
title('Lufttryck','FontSize', tsize);
plot1=plot(plotdata(:,1),plotdata(:,13),'r');
ylabel('hPa','FontSize',ysize);

%% Hourly averaged windspeed and NOT Hourly maximum wind
axes2 = axes('Parent',figure1,...
    'YLim',[0 30],...
    'YTick',[0 5 10 15 20 25 30 35 40],...
    'YTickLabel',[0 {''} 10 {''} 20 {''} 30 {''} 40],...
    'XLim',[n-3 n+1],...
    'Position',[0.12 0.52 0.85 0.07],...
    'FontSize',asize,...
    'XTickLabel',xlabels,...
    'XTick',n-3:2/24:n+1,...
    'TickLength',[0.005 0.1],...
    'YGrid','on');
box('on');
hold('all');
title('Vindhastighet','FontSize', tsize);
%     plot2=plot(plotdata(:,1),plotdata(:,9),plotdata(:,1),plotdata(:,10));
%text(n-3+1,15,'TILLFÄLLIGT UR FUNKTION')
 plot1=plot(plotdata(:,1),plotdata(:,[9 10]));
 set(plot1(1),'DisplayName','Medel','Color',[0 0 0],'LineStyle','-');
 set(plot1(2),'DisplayName','Max','Color',[1 0 0],'LineStyle','-');
 legend1 = legend(axes2,'show');
 set(legend1,'Position',[0.292 0.58 0.01 0.01],'Orientation','horizontal','FontSize',8,...
     'FontName','Arial');
ylabel('m/s','FontSize',ysize);

%% Wind direction
axes3 = axes('Parent',figure1,...
    'YLim',[0 360],...
    'XLim',[n-3 n+1],...
    'Position',[0.12 0.40 0.85 0.07],...
    'FontSize',asize,...
    'XTickLabel',xlabels,...
    'YTickLabel',[0 90 180 270 360],...
    'YTick',0:90:360,...
    'XTick',n-3:2/24:n+1,...
    'TickLength',[0.005 0.1],...
    'YGrid','on');
box('on');
hold('all');
title('Vindriktning','FontSize', tsize);
 plot3=plot(plotdata(:,1),plotdata(:,21));
%text(n-3+1,180,'TILLFÄLLIGT UR FUNKTION')
 set(plot3,'Color',[0 0 1],'LineStyle','none','Marker','.','Markersize',5);
ylabel('grader ( ^o )','FontSize',ysize);

%% Precipitation
axes3 = axes('Parent',figure1,...
    'YLim',[0 3],...
    'XLim',[n-3 n+1],...
    'Position',[0.12 0.28 0.85 0.07],...
    'FontSize',asize,...
    'XTickLabel',xlabels,...
    'YTickLabel',[0 1 2 3],...
    'YTick',0:1:3,...
    'XTick',n-3:2/24:n+1,...
    'TickLength',[0.005 0.1],...
    'YGrid','on');
box('on');
hold('all');
title('Nederbörd (regn)','FontSize', tsize);
plot3=bar(plotdata(:,1),plotdata(:,16)/6,'r','EdgeColor',[1 0 0]);
ylabel('mm/10min','FontSize',ysize);

%% Hail
axes3 = axes('Parent',figure1,...
    'YLim',[0 50],...
    'XLim',[n-3 n+1],...
    'Position',[0.12 0.16 0.85 0.07],...
    'FontSize',asize,...
    'XTickLabel',xlabels,...
    'YTickLabel',[0 25 50],...
    'YTick',0:25:50,...
    'XTick',n-3:2/24:n+1,...
    'TickLength',[0.005 0.1],...
    'YGrid','on');
box('on');
hold('all');
title('Hagel','FontSize', tsize);
plot3=plot(plotdata(:,1),plotdata(:,19)/6);
ylabel('träffar/cm^2','FontSize',ysize);
xlabel('Tid (timma)','FontSize',asize);

%% Water level
% axes5 = axes('Parent',figure1,...
%     'YLim',[-100 100],...
%     'XLim',[n-3 n+1],...
%     'Position',[0.12 0.04 0.85 0.07],...
%     'FontSize',asize,...
%     'XTickLabel',xlabels,...
%     'XTick',n-3:2/24:n+1,...
%     'TickLength',[0.005 0.1],...
%     'YGrid','on');
% box('on');
% hold('all');
% title('Vattennivå','FontSize', tsize);
% 
% %     plot5=bar(plotdata(:,1),plotdata(:,23));
% % set(plot5,'DisplayName','Water Level',[0 0 0],'LineStyle','-');
% text(n-3+1,0,'TILLFÄLLIGT AVSTÄNGD')
% % Create ylabel
% ylabel('cm','FontSize',ysize);
% % Create xlabel
% xlabel('Tid (timma)','FontSize',asize);

%% Dates labes
text(n-3+3.2,-230,datestr(n,29),'FontSize',asize)
text(n-3+2.2,-230,datestr(n-1,29),'FontSize',asize)
text(n-3+1.2,-230,datestr(n-2,29),'FontSize',asize)
text(n-3+0.2,-230,datestr(n-3,29),'FontSize',asize)
%% Save plot for web
savtitle=['Bridge_',datestr(round(n),30),'_sv.png'];
PlotDir=fullfile('C:\MeteorologicalMeasurements\Bridge\Plot\Figures');
figurea=fullfile(PlotDir,savtitle);
set(figure1,'PaperPositionMode','auto')
print(figure1,'-dpng',figurea)

webtitle='Bridge_plot_sv.png';
PlotDir1=fullfile('C:\MeteorologicalMeasurements\Bridge\Plot');
figurea1=fullfile(PlotDir1,webtitle);

set(figure1,'PaperPositionMode','auto')
print(figure1,'-dpng',figurea1)

f=ftp('pc70.gvc.gu.se','urban-net');
cd(f,'public_html');
mput(f,'Bridge_plot_sv.png');

% Tablefigure
last=size(tendata,1);
fsize=5;
figure2 = figure('Position',[500 200 294 100],'color',[1 1 1]);
annotation(figure2,'textbox',[0.00 0.93 0.85 0.1],...
    'String',['Senast hämtade data:     ' datestr(tendata(last,1),'mmmm dd, yyyy HH:MM') ' (CET)'],...
    'LineStyle','none','FontName','Verdana','FontSize',fsize,'FontWeight','bold');
annotation(figure2,'textbox',[0.00 0.03 0.85 0.9],...
    'String',{'Lufttemperatur (120 möh):'
    'Relativ fuktighet (120 möh):'
    'Vindhastighet (120 möh):'
    'Vindriktning (120 möh):'
    'Lufttryck (120 möh):'
    'Nederbörd (regn):'
    'Ackumulerad nederbörd (dygn):'
    'Vattennivå:'},...
    'LineStyle','none','FontName','Verdana','FontSize',fsize);
annotation(figure2,'textbox',[0.55 0.03 0.85 0.9],...
    'String',{num2str(tendata(last,11),'%6.1f')
    num2str(tendata(last,12),'%6.1f')
    num2str(tendata(last,9),'%6.1f')
    num2str(tendata(last,6),'%6.1f')
    num2str(tendata(last,13),'%6.1f')
    num2str(tendata(last,16)/6,'%6.1f')
    num2str(sum(tendata(last-144:last,16)/6),'%6.1f')
    'NA'},... %num2str(tendata(last,23),'%6.1f')},...
    'LineStyle','none','FontName','Verdana','FontSize',fsize,'FontWeight','bold');
annotation(figure2,'textbox',[0.73 0.03 0.85 0.9],...
    'String',{' °C'
    ' %'
    ' m/s'
    ' °'
    ' hPa'
    ' mm/10 min'
    ' mm/24 tim'
    ' cm'},...
    'LineStyle','none','FontName','Verdana','FontSize',fsize);

webtitle='Bridgetable_plot_sv.png';
PlotDir1=fullfile('C:\MeteorologicalMeasurements\Bridge\Plot');
figurea2=fullfile(PlotDir1,webtitle);

set(figure2,'PaperPositionMode','auto')
%     saveas(figure (2), figurea2)
print(figure2,'-dpng',figurea2)

f=ftp('pc70.gvc.gu.se','urban-net');
cd(f,'public_html');
mput(f,'Bridgetable_plot_sv.png');